### ISSUE TITLE
Outdated Marketplace version

### ISSUE THREAD

**Issue by lorenzwalthert** [octokit/request-action#98]
Going to https://github.com/marketplace/actions/github-api-request and click 'use latest version' gives me a version that is lower than the GitHub release version and about one year older:

![Screenshot 2021-05-18 at 11 15 25](https://user-images.githubusercontent.com/10477073/118625799-9c63e000-b7ca-11eb-92e5-b0736f9aff86.png)

Can you align them? Thanks for this cool action 🥳

**Comment by gr2m** [comment]
As long as you use 

```yml
      - uses: octokit/request-action@v2.x
```

as documented in the description, you'll automatically get the latest version.

Publishing new releases to the repository are not automatically replicated to the marketplace, I've been asking for this since the beginning of it all ... I'll fix it now manually but as all releases are automated, this will get out of sync again, unfortunately
